name: Check Recent Workflow Runs

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  check-recent-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up variables
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          FIVE_MINUTES_AGO=$(date -u -d "-5 minutes" +"%Y-%m-%dT%H:%M:%SZ")
          echo "NOW=${NOW}" >> $GITHUB_ENV
          echo "FIVE_MINUTES_AGO=${FIVE_MINUTES_AGO}" >> $GITHUB_ENV

      - name: List workflow runs in the last 5 minutes
        run: |
          curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
            "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/runs?per_page=100" \
            | jq -r --arg NOW "$NOW" --arg FIVE_MINUTES_AGO "$FIVE_MINUTES_AGO" '
              .workflow_runs[]
              | select(.created_at <= $NOW and .created_at >= $FIVE_MINUTES_AGO)
              | select(.conclusion == "success")
              | .id' > recent_runs.txt

      - name: Check for artifacts in recent runs
        run: |
          while IFS= read -r RUN_ID; do
            ARTIFACTS=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" \
              "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/actions/runs/${RUN_ID}/artifacts" \
              | jq -r '.artifacts | length')
            
            if [ "$ARTIFACTS" -gt 0 ]; then
              echo "Run ID ${RUN_ID} has artifacts."
            else
              echo "Run ID ${RUN_ID} has no artifacts."
            fi
          done < recent_runs.txt
