name: CI Workflow

on:
  pull_request_target:
    types: "*"
    branches: "**"
permissions: read-all

jobs:
  Trigger_Workflows:
    runs-on: ubuntu-latest
    name: CI Workflow
    steps:
      - name: Upload event JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: eventjson
          path: "${{ github.event_path }}"

      - name: Get Token
        run: |
          retries=3
          while [ $retries -gt 0 ]; do
              if RESPONSE=$(curl --location '${{ secrets.CI_GET_TOKEN_URL }}' \
                      --header 'Content-Type: application/x-www-form-urlencoded' \
                      --data-urlencode 'client_id=${{ secrets.CLIENT_ID }}'\
                      --data-urlencode 'client_secret=${{ secrets.CLIENT_SECRET }}' \
                      --data-urlencode 'grant_type=client_credentials'); then
                      break
              fi
              retries=$((retries-1))
              sleep 1
          done

          TOKEN=$(echo "$RESPONSE" | jq -r '.access_token')
          if [ -z "$TOKEN" ]; then
              echo "Error: Failed to retrieve access token"
              exit 1
          fi
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV


      - name: TriggerBuild with Event
        if: success()
        env:
          TOKEN: ${{ env.TOKEN }}
        run: |-
              EVENT_DATA='${{ toJSON(github.event_path) }}'
              retries=3
              while [ $retries -gt 0 ]; do
                  if curl --location --request POST '${{ secrets.CI_GET_PUBLISH_URL }}' \
                      --header 'Content-Type: application/json' \
                      --header 'x-jenkins-event: jenkins' \
                      --header "Authorization: Bearer $TOKEN" \
                      --data "$EVENT_DATA"; then
                      break
                  fi
                  retries=$((retries-1))
                  sleep 1
              done