name: dummy-workflow
on:
  pull_request_target:
    types: "*"
    branches: "**"
  pull_request_review:
    types: "**"
permissions: read-all
jobs:
  dummy-workflow:
    runs-on: ubuntu-latest
    name: dummy-workflow
    steps:
      - name: Upload event JSON as artifact
        uses: actions/upload-artifact@v4
        with:
          name: eventjson
          path: "${{ github.event_path }}"
